'use client';

import { useState } from 'react';
import { HardHat, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

export function LoginForm() {
  const [mode, setMode] = useState<'login' | 'register'>('login'); const [phone, setPhone] = useState(''); const [password, setPassword] = useState(''); const [displayName, setDisplayName] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { const response = await fetch(`/api/auth/${mode}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ phone, password, displayName }) }); const data = await response.json() as { error?: string }; if (!response.ok) throw new Error(data.error ?? '操作失败'); window.location.assign('/'); } catch (e) { setError(e instanceof Error ? e.message : '操作失败'); } finally { setSaving(false); } }
  return <main className="grid min-h-screen place-items-center bg-[linear-gradient(145deg,#132c37,#255763)] p-4"><section className="w-full max-w-sm rounded-3xl bg-background p-6 shadow-2xl"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-primary text-primary-foreground"><HardHat /></div><div><p className="text-xs font-bold tracking-widest text-muted-foreground">区域用工信息</p><h1 className="text-xl font-black">工友直连</h1></div></div><div className="mt-6 grid grid-cols-2 rounded-xl bg-muted p-1"><button type="button" className={`rounded-lg py-2 text-sm font-bold ${mode === 'login' ? 'bg-background shadow-sm' : ''}`} onClick={() => setMode('login')}>登录</button><button type="button" className={`rounded-lg py-2 text-sm font-bold ${mode === 'register' ? 'bg-background shadow-sm' : ''}`} onClick={() => setMode('register')}>注册</button></div><form className="mt-5 grid gap-4" onSubmit={submit}>{mode === 'register' && <label className="grid gap-1.5 text-sm font-bold">称呼<Input value={displayName} onChange={(e) => setDisplayName(e.target.value)} maxLength={30} placeholder="例如：王师傅" /></label>}<label className="grid gap-1.5 text-sm font-bold">手机号<Input value={phone} onChange={(e) => setPhone(e.target.value.replace(/\D/g, '').slice(0, 11))} inputMode="tel" placeholder="11位手机号" /></label><label className="grid gap-1.5 text-sm font-bold">密码<Input type="password" value={password} onChange={(e) => setPassword(e.target.value)} minLength={8} maxLength={72} placeholder="至少8位" /></label>{error && <p className="text-sm text-red-600">{error}</p>}<Button className="h-11" disabled={saving}>{saving ? '正在处理…' : mode === 'login' ? '登录' : '注册并登录'}</Button></form><p className="mt-4 flex gap-2 text-xs leading-5 text-muted-foreground"><ShieldCheck className="mt-0.5 size-4 shrink-0" />密码只保存加密结果；手机号不会出现在公开信息列表。</p></section></main>;
}
